# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  variables:
    environment:  myVariable
  jobs:
  - job: InitialBuild
    steps:
    - script: echo Hello, $(environment)
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeploys
    steps:
    - script: echo Hello, world! don change oo
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo Olorunfemi Ifeoluwa Emmanuel.
      displayName: 'Run a multi-line script'

- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeploys
    steps:
    - script: echo Hello, world! don change oo
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo Olorunfemi Ifeoluwa Emmanuel.
      displayName: 'Run a multi-line script'

- stage: ProdDeploy
  dependsOn: 
  - QADeploy
  - DevDeploy
  jobs:
  - job: ProdDeploys
    steps:
    - script: echo Hello, world! don change oo
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo Olorunfemi Ifeoluwa Emmanuel.
      displayName: 'Run a multi-line script'
